<?php

return [
    "storage_disk" => ['disk' => 'public'],
    "icons" => [
        "seoicon-social-instagram",
        "seoicon-social-linkedin",
        "seoicon-quotes",
        "seoicon-loupe-0",
        "seoicon-arrow-back",
        "seoicon-arrow-to-bottom",
        "seoicon-hit-target",
        "seoicon-business-cash",
        "seoicon-business",
        "seoicon-button",
        "seoicon-check",
        "seoicon-check-bold",
        "seoicon-clip",
        "seoicon-clock",
        "seoicon-coins",
        "seoicon-commerce",
        "seoicon-tags",
        "seoicon-chat-comment",
        "seoicon-cross",
        "seoicon-delete-bold",
        "seoicon-delete",
        "seoicon-draw",
        "seoicon-exit-door",
        "seoicon-facebook",
        "seoicon-google",
        "seoicon-help",
        "seoicon-graphic-search",
        "seoicon-hand-thumb",
        "seoicon-mail-send",
        "seoicon-interface",
        "seoicon-left-large-arrow",
        "seoicon-lightbulb-on",
        "seoicon-line-graph",
        "seoicon-loupe",
        "seoicon-loupe-2",
        "seoicon-loupe-3",
        "seoicon-email",
        "seoicon-menu-dots-bold",
        "seoicon-menu-dots",
        "seoicon-musical",
        "seoicon-people",
        "seoicon-basket",
        "seoicon-help-action",
        "seoicon-pie-circular-graphic-with-bars-in-the-center-part-thin-symbol-outline-inside-a-circle",
        "seoicon-pie-graph",
        "seoicon-pie-graph-split",
        "seoicon-pin-map",
        "seoicon-pinterest",
        "seoicon-play-button-arrowhead",
        "seoicon-play",
        "seoicon-right-large-arrow",
        "seoicon-right-arrow",
        "seoicon-rss",
        "seoicon-search",
        "seoicon-search-large",
        "seoicon-search-bold",
        "seoicon-search-outline",
        "seoicon-seo-landing-pages-symbol-inside-a-circle",
        "seoicon-seo-search-symbol",
        "seoicon-settings-symbol-with-up-arrow-in-a-circle",
        "seoicon-shape-heart",
        "seoicon-shapes-play",
        "seoicon-shape-heart-bold",
        "seoicon-shapes",
        "seoicon-zoom",
        "seoicon-social-links",
        "seoicon-social-pinterest",
        "seoicon-social-twitter",
        "seoicon-social-google-plus",
        "seoicon-social-facebook",
        "seoicon-stack",
        "seoicon-strategy",
        "seoicon-Target-Audience",
        "seoicon-target-search",
        "seoicon-text-paper",
        "seoicon-time-is-running",
        "seoicon-link",
        "seoicon-link-bold",
        "seoicon-pin-it",
        "seoicon-twitter",
        "seoicon-wireless-internet-connection-symbol",
        "seoicon-worm-outline-inside-a-circle",
        "seoicon-youtube",
    ],

    "page_title" => [
        "home" => "HOME",
        "about" => "ABOUT",
        "contact" => "CONTACT US",
        "service" => "SERVICE",
        "admin" => [
            "login" => "LOGIN",
            "dashboard" => "DASHBOARD",
            "user" => [
                "add" => "ADD USER",
                "list" => "USER LIST",
            ]
        ]
    ],

    "default_image" => "placeholder.png"


];
